# Generated by Django 5.2.8 on 2025-12-05 14:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Class 6, Class 7", max_length=100, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice Question"),
                            ("cq", "Creative Question"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "mcq_subtype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("simple", "Simple MCQ (A, B, C, D)"),
                            ("combined", "Combined MCQ (i, ii, iii with choices)"),
                        ],
                        help_text="Only applicable for MCQ type",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="Question content with Markdown and LaTeX support"
                    ),
                ),
                (
                    "question_text_html",
                    models.TextField(
                        blank=True, help_text="Rendered HTML version for caching"
                    ),
                ),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.0"), max_digits=5
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "solution",
                    models.TextField(
                        blank=True, help_text="Solution with Markdown and LaTeX support"
                    ),
                ),
                ("solution_html", models.TextField(blank=True)),
                (
                    "hints",
                    models.JSONField(
                        blank=True, default=list, help_text="List of hints for students"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="All questions are accessible to users by default",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether question has been reviewed and approved",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Manager who created this question",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MCQOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "option_text",
                    models.TextField(
                        help_text="Option text with Markdown and LaTeX support"
                    ),
                ),
                ("option_text_html", models.TextField(blank=True)),
                (
                    "option_label",
                    models.CharField(
                        help_text="Label like 'A', 'B', or 'i', 'ii'", max_length=10
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "combined_option_indices",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="For combined MCQ: list of statement indices",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcq_options",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCQ Option",
                "verbose_name_plural": "MCQ Options",
                "ordering": ["question", "order"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "class_level",
                    models.ForeignKey(
                        help_text="Class this subject belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="questions.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subjects_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["class_level", "order", "name"],
                "unique_together": {("class_level", "name")},
            },
        ),
        migrations.AddField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="questions.subject",
            ),
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chapters_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Subject this chapter belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="questions.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapter",
                "verbose_name_plural": "Chapters",
                "ordering": ["subject", "order", "name"],
                "unique_together": {("subject", "name")},
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        help_text="Chapter this topic belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="questions.chapter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topics_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "ordering": ["chapter", "order", "name"],
                "unique_together": {("chapter", "name")},
            },
        ),
        migrations.AddField(
            model_name="question",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="questions", to="questions.topic"
            ),
        ),
        migrations.CreateModel(
            name="UserDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Draft",
                "verbose_name_plural": "User Drafts",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DraftQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_drafts",
                        to="questions.question",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_questions",
                        to="questions.userdraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Draft Question",
                "verbose_name_plural": "Draft Questions",
                "ordering": ["draft", "order"],
            },
        ),
        migrations.CreateModel(
            name="CQSubQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Label like 'a', 'b', 'c'", max_length=10
                    ),
                ),
                (
                    "sub_question_text",
                    models.TextField(
                        help_text="Sub-question text with Markdown and LaTeX support"
                    ),
                ),
                ("sub_question_text_html", models.TextField(blank=True)),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.0"), max_digits=5
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        blank=True, help_text="Answer with Markdown and LaTeX support"
                    ),
                ),
                ("answer_html", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cq_sub_questions",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "CQ Sub-Question",
                "verbose_name_plural": "CQ Sub-Questions",
                "ordering": ["question", "order"],
                "unique_together": {("question", "label")},
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["type", "subject"], name="questions_q_type_9630e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["created_by", "is_active"],
                name="questions_q_created_1d69c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_public", "is_active"], name="questions_q_is_publ_9f75eb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userdraft",
            unique_together={("user", "title")},
        ),
        migrations.AlterUniqueTogether(
            name="draftquestion",
            unique_together={("draft", "question")},
        ),
    ]
