# Generated by Django 5.2.8 on 2025-12-06 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["class_level", "group", "order", "name"],
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
            },
        ),
        migrations.AddField(
            model_name="class",
            name="has_groups",
            field=models.BooleanField(
                default=False,
                help_text="Whether this class has groups (Science, Arts, Commerce). Typically True for HSC and Admission.",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(
                help_text="e.g., Class 6, Class 7, HSC, Admission",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Science, Arts, Commerce", max_length=100
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("science", "Science"),
                            ("arts", "Arts/Humanities"),
                            ("commerce", "Commerce/Business Studies"),
                            ("general", "General"),
                        ],
                        default="general",
                        help_text="Type of group",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "class_level",
                    models.ForeignKey(
                        help_text="Class this group belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="questions.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="groups_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "ordering": ["class_level", "order", "name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="subject",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional group (Science/Arts/Commerce) if the class has groups",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="questions.group",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("class_level", "group", "name")},
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["class_level", "group", "is_active"],
                name="questions_s_class_l_e87a28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["class_level", "is_active"],
                name="questions_g_class_l_028628_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["group_type"], name="questions_g_group_t_2e50cc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("class_level", "name")},
        ),
    ]
