# Generated by Django 5.2.8 on 2025-11-13 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Permission identifier (e.g., 'user.create', 'post.delete')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "codename",
                    models.SlugField(
                        help_text="URL-safe permission code",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of what this permission allows",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("user", "User Management"),
                            ("content", "Content Management"),
                            ("analytics", "Analytics & Reports"),
                            ("settings", "Settings & Configuration"),
                            ("billing", "Billing & Payments"),
                            ("support", "Customer Support"),
                            ("api", "API Access"),
                            ("admin", "Administration"),
                        ],
                        default="user",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "rbac_permissions",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="rbac_permis_name_7e19cb_idx"),
                    models.Index(
                        fields=["codename"], name="rbac_permis_codenam_64fe17_idx"
                    ),
                    models.Index(
                        fields=["category"], name="rbac_permis_categor_86d55f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Role name (e.g., 'Admin', 'Content Manager')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe role identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of role responsibilities and access level",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("system", "System Role"),
                            ("custom", "Custom Role"),
                            ("temporary", "Temporary Role"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (0, "Guest"),
                            (10, "Basic User"),
                            (20, "Premium User"),
                            (30, "Moderator"),
                            (40, "Content Manager"),
                            (50, "Support Agent"),
                            (60, "Manager"),
                            (70, "Admin"),
                            (80, "Super Admin"),
                            (90, "System"),
                        ],
                        default=10,
                        help_text="Role hierarchy level (higher = more privileges)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this role can be assigned to users",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Assign this role to new users by default",
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of users that can have this role (null = unlimited)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inherits_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent role to inherit permissions from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_roles",
                        to="rbac.role",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions granted to this role",
                        related_name="roles",
                        to="rbac.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "rbac_roles",
                "ordering": ["-level", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assigned", "Role Assigned"),
                            ("revoked", "Role Revoked"),
                            ("expired", "Role Expired"),
                            ("modified", "Role Modified"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="rbac.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role History",
                "verbose_name_plural": "Role History",
                "db_table": "rbac_role_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this role assignment is currently active",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary role for the user (used for display)",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Role expiration date (null = never expires)",
                        null=True,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context for role (e.g., workspace_id, project_id)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this role assignment",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="rbac.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "rbac_user_roles",
                "ordering": ["-is_primary", "-assigned_at"],
            },
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["slug"], name="rbac_roles_slug_951461_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["level"], name="rbac_roles_level_6c736d_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["is_active"], name="rbac_roles_is_acti_f056a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolehistory",
            index=models.Index(
                fields=["user", "created_at"], name="rbac_role_h_user_id_8e0585_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolehistory",
            index=models.Index(
                fields=["role", "created_at"], name="rbac_role_h_role_id_755fc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "is_active"], name="rbac_user_r_user_id_a0783d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["role", "is_active"], name="rbac_user_r_role_id_b4929d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["expires_at"], name="rbac_user_r_expires_dfa993_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role", "context")},
        ),
    ]
