# Generated by Django 5.2.8 on 2025-12-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="category",
            field=models.CharField(
                choices=[
                    ("user", "User Management"),
                    ("content", "Content Management"),
                    ("analytics", "Analytics & Reports"),
                    ("settings", "Settings & Configuration"),
                    ("billing", "Billing & Payments"),
                    ("support", "Customer Support"),
                    ("api", "API Access"),
                    ("admin", "Administration"),
                    ("question", "Question Management"),
                    ("draft", "Draft Management"),
                    ("subject", "Subject Management"),
                    ("topic", "Topic Management"),
                    ("payment", "Payment Management"),
                    ("wallet", "Wallet Management"),
                    ("pdf", "PDF Export"),
                ],
                default="user",
                max_length=50,
            ),
        ),
    ]
